### ISSUE TITLE
Checking out to `base_dir: .` causes cleanup to fail

### ISSUE THREAD

**Issue by mgovers-philips** [philips-software/inner-source-checkout-action#153]
## Description

* The winddown step deletes the entire `base_dir`, instead of only the directory to which the repo was cloned.
* When `base_dir` is the current directory `.`, then `.` is deleted
* The built-in Github Actions winddown step also deletes the workspace directory (obviously)
* This causes the workspace directory to be cleaned-up twice, which is illegal, and therefore the action fails

## Example repro:

```yaml
    - name: Checkout utilities
      uses: philips-software/inner-source-checkout-action@v1.1.0
      with:
        token: ${{ steps.token.outputs.token }}
        base_dir: .
        repos: philips-internal/immersive-video-tl-utilities@main
```
