### ISSUE TITLE
Can we combine the get-app-token into this as an option

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/inner-source-checkout-action#19]
Currently we often have to use this action together with the awesome app-token-action:

```
      # Setup private actions
      - name: Get Token
        id: token
        uses: philips-software/app-token-action@1.0.0
        with:
          app_id: <app_id>
          app_base64_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY_BASE64 }}
          auth_type: 'installation'

      - uses: philips-software/inner-source-checkout-action@1.0.0
        with:
          token: ${{ steps.token.outputs.token }}
          base_dir: .actions
          repos: org/repo1@version, org/repo2@version
```

Although this works fine, it is a little bit big.. Can we add an option in `inner-source-checkout-action` to do these two steps in one. Something like:

```
      - uses: philips-software/inner-source-checkout-action@1.0.0
        with:
          app_id: <app_id>
          app_base64_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY_BASE64 }}
          base_dir: .actions
          repos: org/repo1@version, org/repo2@version
```

If `app_id` and `app_base64_private_key` are given instead of `token`, it should get the token itself.
